### ISSUE TITLE
How to jump line in timeline diagram ?

### ISSUE THREAD

**Issue by pinage404** [badboy/mdbook-mermaid#45]
How to jump line in timeline diagram ?

Mermaid version used : 10.9.0

```mermaid
timeline
    2014 : first line<br>second line
```

Expected

![image](https://github.com/badboy/mdbook-mermaid/assets/6325757/195ef754-a678-42a0-a4dd-f5a1bf76175a)

Actual

![image](https://github.com/badboy/mdbook-mermaid/assets/6325757/123c4072-5249-4889-bca5-0534effd4d05)

Maybe related https://github.com/mermaid-js/mermaid/issues/4743

**Comment by badboy** [comment]
Not sure. mdbook-mermaid passes through the content unchanged, mdbook html-escapes it then it seems. By default mermaid.js also seems to disallow HTML tags by default.
I tried it with just HTML and mermaid.js and couldn't get an example to work.

If you do find out I recommend writing that HTML directly instead of using the markdown codeblock. For now I do not plan to change how this plugin behaves.
